### ISSUE TITLE
On some computers, drag and drop of blocks creates visual artefacts

### ISSUE THREAD

**Issue by mbonani** [aseba-community/aseba#157]
ON VPL and on windows, when you drag an d drop a card, the card is shown twice, one time where is you mouse on time a the left high corner.
I cannot make a printsreen to show its disapear on print screen.

**Comment by mbonani** [comment]
still there ;-) 
It is only when I have two monitor. and bug only appear in one of it... (monitor 1)
And when I put the windows over the two monitor the bug is only if I drag from monitor one, and there is not on monitor 2...   so perhaps related with my graphic card....
Very nice  bug I think you cannot fix without my hardware ;-)

**Comment by mbonani** [comment]
Test this morning on another computer (Christophe) and he have it also. But he has same hardware as mine Thinkpad W520. Test on Dany's one (W530) and he as not the bug. So definitively a bug related with our (me and Christophe) graphic card ( I guess).

**Comment by stephanemagnenat** [comment]
Ok, I guess we could not correct or work around this bug for 1.4. I am re-assigning it to 1.5.

**Comment by stephanemagnenat** [comment]
Is it still present with latest driver/Qt 4.x release?

**Comment by mbonani** [comment]
Sorry still there with last build on latest server...

**Comment by stephanemagnenat** [comment]
Ok, well, there is not much one can do now, rescheduling this issue for 1.6...

**Comment by mbonani** [comment]
I just test on 1.5.5 and bug disappear! I will close it.
