### ISSUE TITLE
Allow call of subroutine from initialization code

### ISSUE THREAD

**Issue by stephanemagnenat** [aseba-community/aseba#158]
Currently it is not possible to call subroutines from the initialisation code, because subroutines names are checked in a single pass. This limitation could be lifted by doing the subroutine-name resolution in two passes (collect subroutines names and then check if they are all implemented). This would enable the call of subroutines from the initialisation, which is a useful feature, for instance to setup some variables.

**Comment by stephanemagnenat** [comment]
Implemented in #2b6b25e

**Comment by motib** [comment]
Works OK on Windows.
Thanks!!
