### ISSUE TITLE
Differences between VPL standalone and when run from Studio

### ISSUE THREAD

**Issue by motib** [aseba-community/aseba#243]
Thanks for fixing the Windows installer and for fixing the display of VPL when opened from Studio! However ... it would be nice if the displays were identical.
1. The title bar is different with the standalone giving _important_ information: the version and the file. I know that you are going to say that that information is available in the Studio window, but VPL is on top of Studio so you can't even do alt-tab to toggle between them.
2. The full-screen display of VPL from Studio is great. I would like to suggest that the standalone VPL use (what Java calls) a JSplitPane so that the text area could be adjusted (and minimized by default!).

Moti

**Comment by stephanemagnenat** [comment]
Is this problem still present in 1.4?

**Comment by mbonani** [comment]
I think it is outdated
