### ISSUE TITLE
reordering event-action pairs is not clear

### ISSUE THREAD

**Issue by riedo** [aseba-community/aseba#263]
Sometimes, if i reorder lines in VPL (I use development version, display pairs on 2 columns) new empty lines appear in the middle... Or maybe it's the last empty line that moves in the middle, so a new one is created? it is not very clear to me.

when I drag a pair it would be nice that I can visualise where it will go (e.g. other lines move in real time) (this was the utopic wish part)

**Comment by stephanemagnenat** [comment]
@mbonani and @riedo, is this problem still present in latest 1.4 development versions?

**Comment by mbonani** [comment]
for me it is an old bug related to 1.3.....

**Comment by stephanemagnenat** [comment]
I agree, I close it. @riedo please open it again if the problem is still present in VPL 1.4
