### ISSUE TITLE
File selector goes to install directory

### ISSUE THREAD

**Issue by motib** [aseba-community/aseba#336]
When you create a new file and then click "save as", the file selector defaults to the install directory and not to the "current" directory - the last directory from which a file was opened and/or saved. Similarly, "open" defaults to the install directory and not the current directory.

**Comment by stephanemagnenat** [comment]
The build server is back up, please test the latest build to see whether this issue is still open.

**Comment by motib** [comment]
I don't think so :-(.
This morning is the 8th and the last Windows build is e90cc06 from the 5th.

**Comment by motib** [comment]
Works OK.

**Comment by stephanemagnenat** [comment]
Feel free to close the issue if you are happy with the current behaviour :-)
