### ISSUE TITLE
Run button blicking while grayed-out

### ISSUE THREAD

**Issue by stephanemagnenat** [aseba-community/aseba#338]
On Windows, in some situations, the "Run" button was blicking but was in the same time grayed-out because the program had an error.

**Comment by mbonani** [comment]
still there it blink between two gray scale

**Comment by motib** [comment]
I would never had noticed this if you hadn't pointed it out!!

The intended semantics of the blink is: "don't forget to click me", but if the program has an error, the run button can't be clicked. It's not worth changing if it requires a lot of effort, but if the mod is simple, I am in favor of doing it.

**Comment by stephanemagnenat** [comment]
Fixed in commit 82f2228.
