### ISSUE TITLE
Red indicator on the side of proximity/ground sensor not shown

### ISSUE THREAD

**Issue by stephanemagnenat** [aseba-community/aseba#339]
On certain Windows hosts, the red indicator on the side of proximity/ground sensor is not shown. My guess is that it is a bug in the rendering pipeline on Windows, either on Qt or GDI side.

**Comment by mbonani** [comment]
There is for White, Gray but not in Black is there the red indicator also there on other OS?

**Comment by stephanemagnenat** [comment]
No there is no indicator for black.

**Comment by motib** [comment]
OK in nightly-2015-03-18-aseba-bin-1.3.9-git-842463b-win32.exe

**Comment by stephanemagnenat** [comment]
@mbonani is this problem still present for you? If so, could you have other people at Mobots/Mobsya try to reproduce the problem you have?

**Comment by mbonani** [comment]
It is fine for me now. Do you want I test on other windows? You open the bug based on which version of windows?

**Comment by stephanemagnenat** [comment]
I noticed that bug on some ETH computers during a workshop. I think they were running Windows 7, but I am not sure. Also, it might be a graphic driver bug specific to these computers.

**Comment by stephanemagnenat** [comment]
As it works for several people, I will close this bug. We can re-open it and add more information if the problem re-appears.
