### ISSUE TITLE
VPL Sensor event "between" values

### ISSUE THREAD

**Issue by motib** [aseba-community/aseba#345]
Currently a sensor event is caused in advanced mode in VPL if the value read is below the value specified in the lower slider _or_ above the value specified in the upper slider. I request an option for an event when the value is between the sliders. I found my self needing this when trying to implement something similar to the lightpainting project in VPL.

**Comment by stephanemagnenat** [comment]
@motib this is now implemented with a color coding similar to what @ddoak suggested in issue #347 . As usual, testing is welcome :-)

**Comment by stephanemagnenat** [comment]
@motib please close this issue if you are happy with the current implementation.
