### ISSUE TITLE
VPL "orientation" and "set alarm" blocks - interface proposal

### ISSUE THREAD

**Issue by ddoak** [aseba-community/aseba#348]
Some simple visual changes (see diagram) might possibly improve the interface for the "orientation (acceleration)" and "set alarm / timer" blocks.

![vpl_rotation_handles](https://cloud.githubusercontent.com/assets/7423291/5339798/fa798b00-7edc-11e4-83ed-525765350f23.png)

Why?

**makes interface more self consistent**

* all draggable handles are now similar in style and colour (i.e. compare with the advanced proximity sensor blocks where the sliders have black outline / white fill.
* all rotational handles are now similar to each other in representation (pivot point and draggable arm)

**improves interface usability**

* easier to read - because of improved contrast 
* easier to manipulate - because the handles are bigger (particularly for the timer)

**Potential issues**

1) A possible issue is that for the "orientation" block  this change leaves us with a red mode indicator circle which previously related to the red sector in the icon. Colouring the pivot point of the handle red would keep this association. This also has the advantage of clearly marking the axis of rotation.

![vpl_rotation_handles04](https://cloud.githubusercontent.com/assets/7423291/5341298/9e685d18-7eec-11e4-88fd-90db410037d9.png)

2) I notice that the thymio wheel is very prominent in the side view - presumably this was done to make a clear difference between the side and front views. Adding the pivot circle to the handle slightly obscures this detail. One solution would be for the thymio graphic to be larger so that the wheel remained visible.

As before - I'm not aware of the decision making history leading to the current version - apologies if this is revisiting old ground.

**Comment by stephanemagnenat** [comment]
I have thought about this request, and have some comments:
- For the orientation "handle", its width is actually showing the range, so it is in fact not only an handle. Therefore, if we change its width, it will not display the correct range anymore. Do you have a suggestion to resolve this issue?
- Is the grayscale gradient really useful in the timer action?

**Comment by ddoak** [comment]
* Orientation "handle" - Do you mean that the angle subtended by the arc of the red sector accurately maps to the range? I hadn't noticed - I thought it was just a pointer and I'd made it "chunkier" in the mock-up to make it a bigger mouseclick target. 

* Same thinking for the timer "handle" - it is quite thin and difficult to click - particularly with the poor contrast against the dark blue'. Hence making it wider and improving the contrast in the mock-up.

* Timer grayscale - had no function other than cosmetic (to improve contrast and to tie up with grayscale in the proposed proximity sensor ranges - however I'm guessing that the gradients are a pain to render ;) )

**Comment by stephanemagnenat** [comment]
The timer part is implemented in commit a8df90d.

**Comment by stephanemagnenat** [comment]
The orientation part is implemented in commit 842463b.

After testing, I did not put the small circle at the pivot point as it felt confusing.

**Comment by stephanemagnenat** [comment]
@ddoak, if you are happy with the changes, please close the issue. Thank you!

**Comment by ddoak** [comment]
@stephanemagnenat, looks good. The timer in particular feels much more usable.
