### ISSUE TITLE
Wrong exception raised in vm.c for CONDITIONAL_BRANCH

### ISSUE THREAD

**Issue by supcik** [aseba-community/aseba#388]
The code for CONDITIONAL_BRANCH checks the stack with the following lines (line 422 and followings):

```C++
// check sp
#ifdef ASEBA_ASSERT
if (vm->sp < 1)
	AsebaAssert(vm, ASEBA_ASSERT_STACK_OVERFLOW);
#endif
```

To my understanding, the stack is ascending, so if SP is less that 1, the code should rais a STACK_UNDERFLOW instead of STACK_OVERFLOW.

This would be the matching new code:

```C++
// check sp
#ifdef ASEBA_ASSERT
if (vm->sp < 1)
	AsebaAssert(vm, ASEBA_ASSERT_STACK_UNDERFLOW);
#endif
```
 
The code is actually correct for the BINARY_ARITHMETIC (called by CONDITIONAL_BRANCH).

**Comment by stephanemagnenat** [comment]
Your are right, thanks for reporting! Corrected in commit de5ca2f.
