### ISSUE TITLE
VPL does not interpret pairs in the same order in basic and advanced mode

### ISSUE THREAD

**Issue by riedo** [aseba-community/aseba#390]
A user had a code that behaved differently when switching to advanced mode, without changing anything else. On the screenshots we can see that even though the pairs are in the same order, the "call leds.top(0,0,0)" line is not at the same spot in basic and advanced mode, creating different behaviours.

![basic](https://cloud.githubusercontent.com/assets/1862778/8668786/003a6b30-2a0f-11e5-8e9c-ed7aff329658.png)
![advanced](https://cloud.githubusercontent.com/assets/1862778/8668790/0848362c-2a0f-11e5-8eef-ba2c99739f04.png)

**Comment by stephanemagnenat** [comment]
Interesting. I will have to investigate.

The "bug" label is arguable, as we never specified an order of execution in case of race condition. But I agree that this change is inconvenient for the user.

**Comment by riedo** [comment]
Yes. I remember Moti explained a similar "feature" in scratch when he came to lausanne.
Now this is your project, so you have the power to define what is a bug and what is a feature ;-) 

but i can assure you, users expect that a same sequence of order in a programming language generates the same bytecode. In my opinion it is not just a problem of execution which could illustrate race conditions and such, but a problem of consistency in the way the VPL code is translated to aseba script, making it difficult for users to understand.

**Comment by stephanemagnenat** [comment]
I agree with you, and plan to investigate it, when time permits.

**Comment by stephanemagnenat** [comment]
Fixed in commit 351d5f3, please test and close if it works for you.

**Comment by riedo** [comment]
seems all good :) amazingly quick bugfix

**Comment by stephanemagnenat** [comment]
It was just a typo in the implementation actually, the idea was correct already. But it still took me some time to remember what the idea was ;-)
