### ISSUE TITLE
resizing window in VPL for Thymio

### ISSUE THREAD

**Issue by FrancescoMondada** [aseba-community/aseba#391]
When resizing the main window, the text code sub-window always reappears even if it was hided. To reproduce: open VPL for Thymio, hide the text code and resize the main window. Tested on MAC

**Comment by stephanemagnenat** [comment]
I confirm, I have it here as well, both on OS X and Linux. I will investigate.

**Comment by stephanemagnenat** [comment]
Fixed in commit ee19ace :-)

**Comment by stephanemagnenat** [comment]
Please test an updated build and close the issue if you are happy with the behaviour of the correction.

**Comment by FrancescoMondada** [comment]
Happy!
