### ISSUE TITLE
Error in file aseba/targets/challenge/challenge-textures.qrc

### ISSUE THREAD

**Issue by derlin** [aseba-community/aseba#398]
Hi, I just forked your aseba repo and tried to compile it. Unfortunately, there is a __parse error__ in the `aseba/targets/challenge/challenge-textures.qrc` file, which aborts the compilation.

Line 16: the `</file>` tag misses the `>` character.

Hope this help !

p.s.: I did the change in my forked repo https://github.com/derlin/aseba

**Comment by stephanemagnenat** [comment]
Thank you very much, sorry for this bug. It is fixed by commit 4cae273.
