### ISSUE TITLE
Update icons / names for 1.4 on OS X

### ISSUE THREAD

**Issue by cbarraud** [aseba-community/aseba#416]
Make sure the icons and naming conventions are consistent with agreed scheme (as on Linux)

**Comment by riedo** [comment]
app names are updated but the structure of the aseba folder (with Playground and Challenge in a "simulations" folder) is not implemented yet, bc of libraries linking problems. I will try some other solutions, but not for 1.4.0 release. Should I make another issue out of this?

**Comment by stephanemagnenat** [comment]
Yes, I think it is good to make another issue, for now I can close this one. Thanks a lot for your work!
