### ISSUE TITLE
Quit menu unaccessible from VPL in Studio

### ISSUE THREAD

**Issue by FrancescoMondada** [aseba-community/aseba#432]
In MacOS, when starting VPL in Studio, all menus disappear (which is fine) but the main menu with the quit action is also disabled. The only way to quit is to close the window.

**Comment by stephanemagnenat** [comment]
Is it really a problem to have to close the VPL window?

**Comment by FrancescoMondada** [comment]
Seems to be reasonable in the context of a MAC application where a windows (VPL) is taking over.
