### ISSUE TITLE
crash when save file

### ISSUE THREAD

**Issue by mbonani** [aseba-community/aseba#449]
In master branch Studio crashes when files are saved.
Test on my build and from new server

It works on  ThymioVPL stand alone

**Comment by stephanemagnenat** [comment]
I cannot reproduce on Linux, please run under a debugger and report stack trace.

**Comment by cwalther** [comment]
I can reproduce this on Mac OS X, and can fix it with #454. Can you try if that fixes it for you?

I’m not sure why that crash would not occur on Linux though. Maybe it depends on the Qt version, I’m using 4.8.5.
