### ISSUE TITLE
last open directory in thymioupgrader

### ISSUE THREAD

**Issue by mbonani** [aseba-community/aseba#459]
thymioupgrader do not remember last directory.
it works in my own compilation and not in new buildfarm. 

This is not important.

**Comment by mbonani** [comment]
Ok has you ask this is present on the last buildfarm it alwas open "Documents", but not on my own compilation, it remember correctly the last directorier of open hex. file.

**Comment by stephanemagnenat** [comment]
Actually this is not a bug, this feature was never implemented...

So this is a non urgent wish, delegating to 1.6

**Comment by stephanemagnenat** [comment]
Is it still relevant now that the official firmware is automatically downloaded?

**Comment by stephanemagnenat** [comment]
@mbonani is it still relevant now that the official firmware is automatically downloaded?

**Comment by mbonani** [comment]
This feature seems to work again now...
