### ISSUE TITLE
Crash when TAB with full lines

### ISSUE THREAD

**Issue by cbarraud** [aseba-community/aseba#473]
Hi

My Aseba crashes when I try to indent several lines that touches the right border of the text-code area.

Here is an example:
![1](https://cloud.githubusercontent.com/assets/4930020/12582408/3af28f14-c43d-11e5-8f3e-02790693330b.PNG)
Here I want to indent the couple of line that are highlighted. One hit on the TAB button of my keyborad is OK:
![2](https://cloud.githubusercontent.com/assets/4930020/12582415/4c2f23fa-c43d-11e5-944f-98cab68afd76.PNG)
Two, three... until it reaches the right border, perfectly OK:
![3](https://cloud.githubusercontent.com/assets/4930020/12582437/681ad9a6-c43d-11e5-9836-bd413e60a4b2.PNG)
But here, when I hit TAB, Aseba freezes and crashes:
![4](https://cloud.githubusercontent.com/assets/4930020/12582446/7710c3f8-c43d-11e5-9f1e-7ac5a0e21e78.PNG)

It is dependant on the size of the font. Here, I made the font size bigger (Ctrl + mouse wheel) so that the line of the if is already on two lines:
![5](https://cloud.githubusercontent.com/assets/4930020/12582474/aaf8fdde-c43d-11e5-8eb3-d745800908e5.PNG)
and I cannot hit TAB even once, the first hit kills Aseba.

I even tried a simpler code with just two ridiculously long named variables and it freezes instantly:
![7](https://cloud.githubusercontent.com/assets/4930020/12582533/0b120dfa-c43e-11e5-8c32-188928774be1.PNG)

My Aseba is the 1.4.98 (build git-2868b3e/protocol ver.5) with Dashel 1.1.0. The Thymio connected to it was a Thymio II flashed with firmware V9. I run an ASUS Zenbook with Windows 8.1

Can anyone reproduce that? (my computer already did some strange things with the installer, but it was probably my anti-virus, maybe it's only my computer's problem ^^)

**Comment by cbarraud** [comment]
I tested one more thing out of curiosity. With TABing only one line at a time, there is no problem.

**Comment by stephanemagnenat** [comment]
I confirm this also leads to a freeze here on Linux, but not a crash.

**Comment by stephanemagnenat** [comment]
It seems the problem is due to an infinite loop in `AeslEditor.cpp:778`

**Comment by cbarraud** [comment]
On my computer, it freezes and then, if I try to do something else, it pops up the classical "Aseba stopped working" and then Windows tries to help (or not...)

**Comment by stephanemagnenat** [comment]
Corrected in commit 9469c45.
