### ISSUE TITLE
.abo protocole mismatch

### ISSUE THREAD

**Issue by mbonani** [aseba-community/aseba#476]
You cannot make a correct .abo for older version of firmware with protocol 4. 
It seems it put the aseba protocol version and not the node protocol version inside the abo. It result that you make .abo that is not readable by the node afterwards.

**Comment by stephanemagnenat** [comment]
> You cannot make a correct .abo for older version of firmware with protocole 4.

Could you please clarify the use case when there is a problem? I am not sure which version of Studio and the target you use when this problem appears. Also what do you mean by "You cannot make a correct .abo"?

**Comment by stephanemagnenat** [comment]
I understand what you mean.

**Comment by stephanemagnenat** [comment]
Should be corrected by commit 5ff98e8, please test and close if so.

**Comment by mbonani** [comment]
works
