### ISSUE TITLE
Command line upgrading of Thymio firmware might be broken

### ISSUE THREAD

**Issue by dblanchet** [aseba-community/aseba#479]
Hi,

I'm currently trying to upgrade my Thymio-II from V8 to V9 on a MacBookPro (El Capitan, Aseba 1.4).

I tried to launch "Thymio Firmware Upgrader.app", but I get this error message: 
 
<img width="383" alt="capture d ecran 2016-02-07 a 18 01 54" src="https://cloud.githubusercontent.com/assets/845542/12873701/9ea3aa9e-cdc4-11e5-8b81-6ec336e931b4.png">

Note that I can start program from VPL or Aseba Studio. Prior to 1.4, I had to choose suitable port, but not anymore with 1.4.

When I tried with `asebacmd`, I had to find the suitable port name and launched:

`bin/asebacmd -t "ser:name=usbmodem1421" wusb 1 /Users/deob7521/Downloads/Thymio2-V9.hex`

The thymio changed its upside LED color and the command-line stalled to:

```
Found usbmodem1421 on port /dev/cu.usbmodem1421
Flashing /Users/deob7521/Downloads/Thymio2-V9.hex
In bootloader, about to write 64 pages
Writing page 1... Waiting ack ...
```

What am I missing ?

**Comment by stephanemagnenat** [comment]
El Capitan changed the naming of the serial port (changing "-" into "_"), Aseba 1.5, to be released in the next two weeks, works around this problem.

I will check tomorrow whether the command line flasher works on my computer.

**Comment by dblanchet** [comment]
Thank you for quick feedback. I'll give a try to the development version ASAP.

**Comment by dblanchet** [comment]
OK, I was able to update to V9 with dev version (Aseba-136.dmg) of the "Thymio Firmware Upgrader.app". I don't know if (and how) I can help you with command-line behaviour.

Thank you for your help.

**Comment by mbonani** [comment]
The command line written by dblanchet is incomplete: "reset" is missing at the end. 
After testing on all platform I think there is no problem with the falsher in command line. 
I let you close
