### ISSUE TITLE
Change values of IR sensors instead of Something or Nothing

### ISSUE THREAD

**Issue by cbarraud** [aseba-community/aseba#480]
In Blockly for Thymio, a teacher asked me if we could add a feature so that we could type the value of the IR sensors in the if test instead of "detecting proximity".

**Comment by motib** [comment]
I have experienced significant variation in the response of the IR sensors so I regard this feature as essential.

**Comment by stephanemagnenat** [comment]
Ok, we can think about it for 1.6

**Comment by mbonani** [comment]
Having play more with blockly I think it is already possible to use value. But you have to use more blocks for that. See this example: 

![blockly sensor value](https://cloud.githubusercontent.com/assets/1000934/20576680/2b67433a-b1bf-11e6-861d-4a6481a93998.png)

**Comment by stephanemagnenat** [comment]
@cbarraud and @motib, does @mbonani's answer solves your issue?

**Comment by motib** [comment]
I don't use Blockly. I was just supporting the issue that Christhophe raised, so I can't comment on the adequacy of the solution.

**Comment by cbarraud** [comment]
The solution of Michael is indeed working. Closing the issue.
