### ISSUE TITLE
Mispell in the Wireless Configurator (in French)

### ISSUE THREAD

**Issue by cbarraud** [aseba-community/aseba#490]
Hello

Podge from the Wiki spoted a mispell in the french version of the Wireless configurator GUI:

![image](https://cloud.githubusercontent.com/assets/4930020/14411652/e5eef65e-ff4e-11e5-9fc1-8a9281338d08.png)

Enregister instead of Enregist**_r_**er

++

**Comment by stephanemagnenat** [comment]
Fixed in commit dea7c78.
