### ISSUE TITLE
Reconnection problem, doesn't go back to Blockly

### ISSUE THREAD

**Issue by cbarraud** [aseba-community/aseba#491]
Hello

A teacher sent us a mail, I tested and I think there is something wrong with the reconnection process of Blockly.

The thing is, when you code something with Blockly, then disconnect your robot and reconnect it, it doesn't go back to Blockly, but to Aseba Studio. Here is my example:

![image](https://cloud.githubusercontent.com/assets/4930020/14491712/cb388d60-017a-11e6-80a1-442e5b428e6b.png)

I did this code, then unplugged the robot, everything is ok:

![image](https://cloud.githubusercontent.com/assets/4930020/14491718/ddca466c-017a-11e6-99a3-402cf2382295.png)

and then, when I re-plug Thymio, it goes back to Aseba Studio

![image](https://cloud.githubusercontent.com/assets/4930020/14491738/f82d7254-017a-11e6-81f8-3e4f253f7df2.png)

I'm on Windows 8.1 (the teacher was on 7). Aseba version:

![image](https://cloud.githubusercontent.com/assets/4930020/14491755/0b87525c-017b-11e6-9f62-1f07d5747603.png)

**Comment by stephanemagnenat** [comment]
I confirm the problem, it also happens on Linux, I will look into it as soon as possible.

**Comment by stephanemagnenat** [comment]
It is a bug in the Blockly integration indeed, it should be fixed by commit e8bbefdc84d21ba14240c1235a1e8742ff1fd838. Please check the generated build, and close if the problem is solved for you.

**Comment by stephanemagnenat** [comment]
@cbarraud please close the issue if the problem has been solved on your side, thank you :-)

**Comment by cbarraud** [comment]
It's ok on my side, thank you :+1: 

Closing the issue ;)

**Comment by mbonani** [comment]
test on mac Os 10.6 and 10.11 should work in between.
