### ISSUE TITLE
Text more user-friendly when deconnection or when Thymio is not plugged

### ISSUE THREAD

**Issue by cbarraud** [aseba-community/aseba#493]
The texts of the pop-up windows when Thymio is not plugged is not that user-friendly. For example, ThymioVPL says that when you try to start it without a robot:

![image](https://cloud.githubusercontent.com/assets/4930020/14554559/1927fea6-02ee-11e6-9004-6a491cd40341.png)

The Thymio Firmware upgrader is much more user-friendly:

![image](https://cloud.githubusercontent.com/assets/4930020/14554592/439c35d0-02ee-11e6-832a-fe0b2988c79d.png)

We could find friendlier message ;) and maybe think also to add something about the Wireless...?

**Comment by stephanemagnenat** [comment]
This is already implemented in commit 71a23929d5c911579ee88edbf286c96d433a7453.

**Comment by mbonani** [comment]
For this implementation is that here possible to add an image? If not, can you just add also the dongle.

**Comment by stephanemagnenat** [comment]
Image should be easy to add, at worst we subclass the dialog, so yes :-)

Dongle added to text in commit d701e8e.

**Comment by mbonani** [comment]
Ok for me, it is good or the moment, we can think about an image later.
