### ISSUE TITLE
Add image when Thymio is not plugged when you launch specific aseba or VPL

### ISSUE THREAD

**Issue by mbonani** [aseba-community/aseba#494]
We already make the text more friendly, it is just a wish to add an image like the one you have when you disconnect the robot.

**Comment by stephanemagnenat** [comment]
I am not sure to understand. What do you mean by _specific Aseba or VPL_?

**Comment by mbonani** [comment]
When you launch "Aseba studio for Thymio" or "VPL". Sorry I should be more precise.

**Comment by stephanemagnenat** [comment]
If I understand correctly, you would like the application to remember that it was given a specific target, and try to reconnect until it succeeds, right? If so, it makes sense.

I'll move this to 1.7, excepted if you have use cases why it should be urgent and put into 1.6.

**Comment by stephanemagnenat** [comment]
Superseeded by #728.
