### ISSUE TITLE
automatic taking of last firmware do not work on Windows 10

### ISSUE THREAD

**Issue by mbonani** [aseba-community/aseba#499]
have seen it to late after I release... sorry.
I have no idea what is hapenenig, probablay a firewall or something like that... have to better understand what is happening

**Comment by stephanemagnenat** [comment]
We can have a look together on Monday, do you have a computer with Windows 10 at Mobots?

**Comment by mbonani** [comment]
We have the surface pro at mobsya
I will take it
My win 10 at home do not work well... it crashed when I launch the firewall
page... progress ;-)
Le 23 avr. 2016 16:20, "Stéphane Magnenat" <notifications@github.com> a
écrit :

**Comment by stephanemagnenat** [comment]
This was a Windows packaging bug, fixed in commit aseba-community/aseba-windows#25c16926120e7c8c452c2d3a771de77971fb7afa.
