### ISSUE TITLE
CLI tool to connect wireless thymios

### ISSUE THREAD

**Issue by show0k** [aseba-community/aseba#525]
Hi,
Is there any CLI program to connect/pair wireless Thymios ? 
I would like to remote control Thymios from an embedded computer with the HTTP interface, and the necessity of a GUI make it harder to do.

**Comment by show0k** [comment]
I just understand that the Wireless GUI is only to pair one thymio to one hardware key. The default behaviour is to connect to every thymios.

**Comment by stephanemagnenat** [comment]
Support has been added in latest master branch, see commits 0b8ff42 and
4c8e2ab.

**Comment by show0k** [comment]
Great, thanks !
