### ISSUE TITLE
Sequential programming mode

### ISSUE THREAD

**Issue by stephanemagnenat** [aseba-community/aseba#537]
Some users of Thymio have expressed the desire to have a sequential programming mode in Blockly, similar at the interface level to what is available with Scratch (similar blocs), but fully running in the robot.

**Comment by ddoak** [comment]
I agree that this would be useful.

In my experience children always expect the thymio blockly implementation
to work sequentially (like Scratch).

**Comment by cor3ntin** [comment]
This issue was moved to aseba-community/blockly#19
