### ISSUE TITLE
problème pda

### ISSUE THREAD

**Issue by bertrand432** [aseba-community/aseba#541]
Bonjour,
j'essaie d'installer aseba sur ubuntu 3.13 mais la commande: sudo add-apt-repository ppa:stephane.magnenat/`lsb_release -c -s`
ne marche pas,
il ne reconnait pas le nom ou le format ppa
est-ce normal? y a t il un autre lien?
merci beaucoup
B Gonnet

**Comment by stephanemagnenat** [comment]
Essayez de taper `lsb_release -c -s`, puis de copier/coller à la main le résultat après `sudo add-apt-repository ppa:stephane.magnenat/`, sans espace. Je pense qu'il y a une erreur de copier/coller de votre côté.

Lors de rapport de bogue, veuillez donner l'erreur exacte produite par le système, ainsi que les commandes qui ont conduit à cette erreur.

**Comment by bertrand432** [comment]
Bonjour M Magnenat,
cela ne marche toujours pas,
je vous envoie une capture d'écran.
j'ai en fait ubuntu 14.04
merci de votre aide
B Gonnet

Le 3 août 2016 à 22:36, Stéphane Magnenat <notifications@github.com> a
écrit :

**Comment by stephanemagnenat** [comment]
Votre capture d'écran n'a pas été attachée au rapport de bug. Normalement vous pouvez clisser-déposer un fichier dans la zone de texte d'un commentaire et il se fait attacher.

**Comment by stephanemagnenat** [comment]
Ce problème est-il toujours présent ?

**Comment by bertrand432** [comment]
Bonsoir,

en fait j'ai laissé tombé.

Je reprendrai les tests pendant les vacances de Noël.

Très cordialement

B Gonnet

2016-12-05 14:54 GMT+01:00 Stéphane Magnenat <notifications@github.com>:

**Comment by bertrand432** [comment]
Bonsoir,
j'ai toujours le même souci.
Je vous joins une capture d'écran.
J'ai vu dans la doc qu'il faut brancher le robot avant de lancer le
logiciel.
Peut-on coder sans le robot?

Très cordialement et bonne année 2017

B Gonnet


Le 6 décembre 2016 à 20:25, Bertrand Gonnet <gonnetbertrand@gmail.com> a
écrit :

**Comment by bertrand432** [comment]
Bonjour,
j'ai pu installer le logiciel manuellement
cordialement
B Gonnet

Le 1 janvier 2017 à 23:43, Bertrand Gonnet <gonnetbertrand@gmail.com> a
écrit :
