### ISSUE TITLE
Aseba Playground: ground textures sometimes disappear

### ISSUE THREAD

**Issue by davidjsherman** [aseba-community/aseba#571]
Observed on macOS, for Aseba Playground with the new Enki libraries.

Sometimes, for certain playgrounds, the ground texture is hidden by a white rectangle that also masks the grey bar across the bottom. I have observed this consistently with the Yeti and Otter playgrounds, but never with the Maze 6x6 playground.

Furthermore, the ground texture disappears while an object is being moved through picking.

**Comment by stephanemagnenat** [comment]
It also appears on Linux.

**Comment by stephanemagnenat** [comment]
Fixed in enki commit enki-community/enki@602e3dd8cff678c27a3b0e4bc888637523b68707.
