### ISSUE TITLE
Thymio VPL RC blocks

### ISSUE THREAD

**Issue by mbonani** [aseba-community/aseba#572]
In advance mode with the RC blocks there is  an strange behavior in generated code when you unchek a RC button. It should not be possible.

**Comment by stephanemagnenat** [comment]
Could you please give a detailed way to reproduce the problem? Thank you.

**Comment by mbonani** [comment]
yes you take a RC blcok and you click on the checked button, you will have a block without  any button checked and an strange generated code.

**Comment by stephanemagnenat** [comment]
Confirmed, working on it.

**Comment by stephanemagnenat** [comment]
Fixed on commit 78c5bb7.
