### ISSUE TITLE
strange behavior sometimes with blockly

### ISSUE THREAD

**Issue by mbonani** [aseba-community/aseba#575]
I just see in live demo of Francesco the temperature sensor block that was frozen. Even if we close the blocky windows,  when we reopen blocky, the block was still there and froze the compiler.
Restart studio resolve the problem
No receipt to reproduce the bug... sorry.

**Comment by stephanemagnenat** [comment]
Which version?

**Comment by mbonani** [comment]
1.53 release. Perhaps fixed.

**Comment by stephanemagnenat** [comment]
Please test with 1.5.4

**Comment by mbonani** [comment]
cannot reproduce with windows 1.5.4. But bug was on a mac OSX with 1.5.3. I let you decide if we can close.

**Comment by stephanemagnenat** [comment]
Let's keep it open until we have the final 1.5.4 package for OS X and let's test with that one.

**Comment by stephanemagnenat** [comment]
Could you try to reproduce this problem with latest OS X packages?

**Comment by stephanemagnenat** [comment]
@mbonani can you check whether this issue is still open.

**Comment by cor3ntin** [comment]
Blockly is being removed from studio.
