### ISSUE TITLE
Display bug for ELSE in the IF condition

### ISSUE THREAD

**Issue by FrancescoMondada** [aseba-community/aseba#577]
When taking the IF block in blockly, activating the ELSE condition is very complex and with display bug on MACOSX (10.8.5) with aseba studio 1.5.3
![screen shot 2016-11-24 at 12 19 52](https://cloud.githubusercontent.com/assets/1001392/20596834/b1ea2784-b240-11e6-89dd-e013342b8974.png)

**Comment by mbonani** [comment]
I confirm on different OSX I have tested this strange black display bug. Nothing on Windows

**Comment by stephanemagnenat** [comment]
This needs to be tested with the new Qt WebEngine which is available in recent Qt 5 distributions.

**Comment by cor3ntin** [comment]
The development of blockly is now happening in

https://github.com/aseba-community/blockly
https://github.com/aseba-community/thymio-blockly-standalone
