### ISSUE TITLE
Srolling the menu window generates a selection

### ISSUE THREAD

**Issue by FrancescoMondada** [aseba-community/aseba#578]
On MACOSX (10.8.5) and Blocly included in Studio 1.5.3, there is a problem of selection of the items in the menus of commands. To be reproduced: start studio, activate blockly, click on one of the menus of orders (for instance "actioneurs", point on one of the item (the item is activated) and scroll (using the trackpad). The item is selected and placed.
The scroll functionality has also strage behaviors on the main window...

**Comment by mbonani** [comment]
Do not happen in Windows, 
But the scrolling is not working at all. No reaction in blockly when you scroll.

**Comment by stephanemagnenat** [comment]
This needs to be tested with the new Qt WebEngine which is available in recent Qt 5 distributions.

**Comment by stephanemagnenat** [comment]
It would be interesting to run the current blockly code in a Qt WebEngine widget in Qt5 to see if this bug has disappeared.

**Comment by cor3ntin** [comment]
The development of blockly is now happening in

https://github.com/aseba-community/blockly
https://github.com/aseba-community/thymio-blockly-standalone
