### ISSUE TITLE
Upgrade Aseba to Qt5

### ISSUE THREAD

**Issue by stephanemagnenat** [aseba-community/aseba#588]
Qt 4 is not supported any more on recent Apple systems, so it becomes an increasingly heavy burden to use it.

The proper thing to do is to migrate Aseba (and Enki) to Qt 5. Preliminary work including Studio (but not the simulators as Enki is not ported yet) is available on the qt5 branch https://github.com/aseba-community/aseba/tree/qt5.

**Comment by cor3ntin** [comment]
Fixed
