### ISSUE TITLE
Playground should be documented in the wiki

### ISSUE THREAD

**Issue by stephanemagnenat** [aseba-community/aseba#597]
Preliminary help is available here: https://www.thymio.org/en:thymiosimulation

The following things should be done:
- [x] The dialogue box screenshot should be updated to reflect the support of zeroconf.
- [x] The page should be translated.

**Comment by mbonani** [comment]
translation is done in EN,FR,DE,IT

**Comment by stephanemagnenat** [comment]
@mbonani should we close this issue?

**Comment by mbonani** [comment]
yes
