### ISSUE TITLE
uint64 definition conflicts with opencv

### ISSUE THREAD

**Issue by marvelous** [aseba-community/aseba#604]
The uint64 type defined in common/types.h conflict with the same name in opencv.
Could we replace this type with c++11 `<cstdint>` or c99 `<stdint.h>`?

**Comment by stephanemagnenat** [comment]
The potential problem is that this header might be built for microcontrollers, for which one cannot be sure that c99 is available.

However, it seems that all recent SDK for embedded systems provide `stdint.h`, so ok to change.
