### ISSUE TITLE
Standalone execution of Blockly

### ISSUE THREAD

**Issue by motib** [aseba-community/aseba#616]
It should be possible to execute Blockly directly from a desktop icon (like VPL). This is important in the context of a school, especially an elementary school.

**Comment by stephanemagnenat** [comment]
Yes, it would be good.

**Comment by motib** [comment]
Same as #8 in Blockly

**Comment by cor3ntin** [comment]
This is being worked for 1.6
The development of bloclky is now happening in

- https://github.com/aseba-community/blockly
- https://github.com/aseba-community/thymio-blockly-standalone
