### ISSUE TITLE
Save/discard from Blocky and Studio

### ISSUE THREAD

**Issue by motib** [aseba-community/aseba#617]
When leaving Blockly, it asked you to save/discard if even the source code is up to date. Furthermore, whatever you decide, Studio asks again the same question.

**Comment by motib** [comment]
Same as #8 in Blockly

**Comment by cor3ntin** [comment]
The development of blockly is now happening in

https://github.com/aseba-community/blockly
https://github.com/aseba-community/thymio-blockly-standalone
