### ISSUE TITLE
Aseba crashes if an array with 40 or more elements is sent as an event.

### ISSUE THREAD

**Issue by tjenni** [aseba-community/aseba#619]
If I execute the following programm, Aseba Studio crashes if N=40 or bigger. For N=5 the program works correctly.
```
# initialize map
var map[N]
var i = 0

while  i < N do
	map[i] = 1
	i = i + 1
end

# send map as an event
onevent button.left
emit sendMap map
```

**Comment by stephanemagnenat** [comment]
Which target do you use? A Thymio, a simulated Thymio, a dummy node?

**Comment by tjenni** [comment]
I use a Thymio II robot and Aseba runs on macOS Sierra.

**Comment by stephanemagnenat** [comment]
This bug appears to be a Thymio wireless bug. I can reproduce it with Thymio Wireless using Linux and OS X, but not with the same Thymio using the USB cable or with dummynode.

It seems that messages of 40 elements or more are truncated into invalid Aseba messages.

**Comment by stephanemagnenat** [comment]
As this is a Thymio wireless bug, a corresponding issue has been opened aseba-community/aseba-target-thymio2#22.

**Comment by mbonani** [comment]
fixed
