### ISSUE TITLE
Creating a global event allows size over 258

### ISSUE THREAD

**Issue by mbonani** [aseba-community/aseba#625]
You cannot change global event size over 258 but you can do it  when you create it. I make an inconstancy

**Comment by stephanemagnenat** [comment]
You means one can create a global event over 258 in length in Studio?

**Comment by mbonani** [comment]
yes I mean "Nombre d'argument"
I was testing relate to : https://github.com/aseba-community/aseba-target-thymio2/issues/22
with USB Thymio about size of globale event we can make and you can compile a program with a map of lengh of  500, you can see in the memory but cannot send it over 258.
