### ISSUE TITLE
Left-click when holding right click on an object makes it disappear.

### ISSUE THREAD

**Issue by Vincebecker** [aseba-community/aseba#632]
In the simulator, if you select a robot by left clicking on it, and then, you hold right click and left-click again, this time outside the robot, the robot (or object) disappears.

**Comment by stephanemagnenat** [comment]
Confirmed, this is an Enki viewer bug, see https://github.com/enki-community/enki/issues/41.

**Comment by stephanemagnenat** [comment]
Fixed by enki commit enki-community/enki@d7ed62e2889055bbdb7dce7a8455726589015427.
