### ISSUE TITLE
Why class Zeroconf does not inherits from class std::vector<Target>?

### ISSUE THREAD

**Issue by stephanemagnenat** [aseba-community/aseba#635]
Class `Zeroconf` has a member `targets` of type `std::vector<Target>`, and recopies a significant part of the interface of `std::vector<Target>`. Is this encapsulation useful? Why not inheriting publicly from `std::vector<Target>`?

**Comment by stephanemagnenat** [comment]
A related question is why, in class `Zeroconf`, the wrappers for the members of `std::vector<Target>` are virtual?

**Comment by marvelous** [comment]
Is Zeroconf a vector? Sorry to bikeshed here, but wouldn't it be cleaner to expose the `targets` member with a reference getter and remove all these methods?

**Comment by stephanemagnenat** [comment]
> expose the targets member with a reference getter

Or just make it public. @davidjsherman what was the rationale behind the current design?

**Comment by stephanemagnenat** [comment]
Currently changing the code to make it public.

**Comment by stephanemagnenat** [comment]
Changed in commit 5fa41768fcbead37f5ce01f49c39c5d976d148ad.
