### ISSUE TITLE
DashelhubZeroconf never erase entries in zeroconfStreams

### ISSUE THREAD

**Issue by stephanemagnenat** [aseba-community/aseba#646]
While `DashelhubZeroconf` adds elements to its map `zeroconfStreams`, it never deletes them. This leads to leaks. The solution is probably to override `Dashel::Hub::connectionClosed()` and erase the stream there.

**Comment by davidjsherman** [comment]
Need to verify life cycle of `serviceRef` because the Zeroconf polling socket is closed only when the serviceRef is freed.
