### ISSUE TITLE
Zeroconf lacks the ability to remove a target from listing

### ISSUE THREAD

**Issue by stephanemagnenat** [aseba-community/aseba#649]
Function `DNSServiceRefDeallocate` should be called on DNSServiceRef, which is done in the destructor of `DiscoveryRequest`. However, the corresponding fd must be removed from the select, which is not the case in subclasses now.

**Comment by davidjsherman** [comment]
https://developer.apple.com/library/content/documentation/Networking/Conceptual/dns_discovery_api/Articles/registering.html#//apple_ref/doc/uid/TP40002478-SW1

**Comment by stephanemagnenat** [comment]
Actually, the destructor of `DiscoveryRequest` does that, so removing a target from `Zeroconf::targets` should de-register the service.

**Comment by stephanemagnenat** [comment]
Fixed by adding a `forget()` function to Zeroconf in c40826348a0ca94367f0b6a15e773d1311a3efe8.
