### ISSUE TITLE
Thymio VPL (standalone) text code erase by selecting and typing enter

### ISSUE THREAD

**Issue by cbarraud** [aseba-community/aseba#660]
In Thymio VPL Standalone, when you create a program and have the text displayed on the side, if you select with your mouse part of text and click on the "Enter" key, the selected text is erased. It doesn't do that with any other key I tested. 

If you do this program for example:
![image](https://user-images.githubusercontent.com/4930020/27957992-516a8056-6321-11e7-9b31-cb80963f5d9c.png)

and then select some text like the green light call, when you type "Enter", it erases. 

![image](https://user-images.githubusercontent.com/4930020/27958019-6d4990c8-6321-11e7-8356-5ffde6ea3822.png)

If you click then on "Play" in VPL, the program downloaded is the one without the green light. 

If you change one single thing in the program (adjust a color, change a button...) the text is retyped. 

I don't know how it is managed, but it could be a good idea to forbid the use of the "Enter" key here, or you can mess up with your code :)

Thymio VPL Version 1.5.98
![image](https://user-images.githubusercontent.com/4930020/27958115-e152e4e2-6321-11e7-9c59-fe6c9572a3f1.png)

Computer with Windows 8.1

**Comment by stephanemagnenat** [comment]
Fixed by commit b7135ce.

**Comment by cbarraud** [comment]
That was quick 👍
