### ISSUE TITLE
Two contradictory actions possible

### ISSUE THREAD

**Issue by FrancescoMondada** [aseba-community/aseba#663]
On VPL mobile, two opposite actions on motors or colors are accepted, the last wins...

![screenshot_20170709-125622](https://user-images.githubusercontent.com/1001392/27997159-840ec4fe-64f2-11e7-9e85-f7a68aabcd6a.png)

**Comment by marvelous** [comment]
This issue is tracked in aseba-community/thymio-vpl2#10
