### ISSUE TITLE
blockly does not launch correctly in master branch on windows

### ISSUE THREAD

**Issue by mbonani** [aseba-community/aseba#665]
![image](https://user-images.githubusercontent.com/1000934/28012464-25294c06-6566-11e7-92c5-1a1f7474a18e.png)

**Comment by stephanemagnenat** [comment]
Interesting, could it be that the Qt you use to compile does not have WebKit support enabled?

**Comment by mbonani** [comment]
It is from the EPFL buildfarm. Also the same on my computer, both have the msys2 compiler installed following the compile.Windows.md instructions

**Comment by mbonani** [comment]
After Stephane investigation the problem come from the qtwebkit compiled from the new compiler. We have differents solutions:
- work to make the webbase solution (actual sandbox) more usable
- recompile QT 4 with the new compiler
- pass to QT5
We will make a small survey to get data from users.

**Comment by cor3ntin** [comment]
Blockly removed from studio
