### ISSUE TITLE
Add duplicate / copy code function to VPL label:wish, VPL

### ISSUE THREAD

**Issue by tiemes** [aseba-community/aseba#669]
There is no way to copy a given line of code in VPL. It would be extremely convenient being able to do so. A lot of time, I only have to change something litte but I still have to drag/drop and click every single item again to do so. Copying would save me a lot of time, effort and reduce the risk of errors.

**Comment by stephanemagnenat** [comment]
You can, by using the **Ctrl** (Windows and Linux) or _Apple_ (macOS) key and drag-and-dropping the line to another one.
