### ISSUE TITLE
Crash of Asebahttp

### ISSUE THREAD

**Issue by cbarraud** [aseba-community/aseba#672]
Hello

I was testing ScratchX with Elisa and Joel when my asebahttp crashed completely. I took a printscreen here:

![image](https://user-images.githubusercontent.com/4930020/28453058-c1057fa4-6df5-11e7-959b-1253f36c9c8c.png)

It is not easy to reproduce though... I was just manipulating the ScratchX program when it crashed. I will try to find a way to reproduce that. The program I did on ScratchX was a loop that turn on and off motors or LED to try to measure the time delay we had in these commands.

I was using

- Wireless Thymio, firmware 10
- Windows 8.1
- Chrome
- aseba-bin-1.5.98-git-84f1a55-win32

**Comment by davidjsherman** [comment]
I think “trying to wait on more than 64 events” is aseba-community/dashel#14: there is a bug in the Windows implementation that will overflow the internal buffer. See [my comment](https://github.com/aseba-community/dashel/issues/14#issuecomment-205939981).

More generally, I agree that asebahttp needs to be made more robust. We lost precious time yesterday tracking down a connection error.

**Comment by cor3ntin** [comment]
That was fixed in 1.6
