### ISSUE TITLE
Add Zeroconf to asebaswitch

### ISSUE THREAD

**Issue by davidjsherman** [aseba-community/aseba#679]

**Comment by davidjsherman** [comment]
See #680 based on [davidjsherman/aseba:679-add-zeroconf-to-asebaswitch](https://github.com/davidjsherman/aseba/tree/679-add-zeroconf-to-asebaswitch)

**Comment by stephanemagnenat** [comment]
Zeroconf in the switch is not critical for 1.6 release, but for http it is. I am moving this issue to 1.7, ok for you @davidjsherman?

**Comment by stephanemagnenat** [comment]
Implementation completed by f0b2c136a252a12448969e9797be4370b700e9a9.
