### ISSUE TITLE
Provide Thymio-specific connection dialogue

### ISSUE THREAD

**Issue by cbarraud** [aseba-community/aseba#694]
I find this new connection interface pretty neat! :))

I am just afraid it might be a bit technical for teachers in terms of which is which. Differentiate the local simulated robots from the USB or Wireless ones is easy when technical data such as "local serial port" doesn't scare you
￼
![image](https://user-images.githubusercontent.com/4930020/30968813-ccc945f4-a460-11e7-9f51-5eb1a196bf76.png)

My only criticism would be that we could have a more user friendly GUI like with buttons or anything.

I made a quick drawing, more explicit than words. It's ugly, but you will get the jizz.

![gui connexion](https://user-images.githubusercontent.com/4930020/30968825-dc26d6c4-a460-11e7-9ed1-f4fdc89a0dda.png)

What do you think? This could become a wish.

**Comment by stephanemagnenat** [comment]
The idea of using categories is interesting, but complications too much the generic Aseba GUI, as there might be a lot of different categories of robots.

If the combination of this generic GUI and the single connection to the first Thymio is not enough, I suggest to make a Thymio-specific dialogue within the Thymio launcher. That would also filter out things such as Bluetooth ports, etc.

**Comment by cbarraud** [comment]
> I suggest to make a Thymio-specific dialogue within the Thymio launcher

I like the idea. It might also be more clever to do that in a more specific Thymio part such as the Thymio launcher instead of the generic Aseba launcher.

**Comment by stephanemagnenat** [comment]
I've changed the title to reflect our discussion.

**Comment by mbonani** [comment]
Just to come back at the original discussion two generic categories could be "local" (local robot connected), and "on network", and put alos robot of local simulator in first category

**Comment by stephanemagnenat** [comment]
It is indeed a good idea, to try to resolve the hostname and see if it is on the machine.

**Comment by stephanemagnenat** [comment]
I'm closing this in favour of #728, a launcher-specific issue.
