### ISSUE TITLE
Thymio Web Bridge blocked by Antivirus

### ISSUE THREAD

**Issue by paolorossetti** [aseba-community/aseba#697]
A professor from Turin wrote me this request for support for aseba-bin-1.5.98-git-c010fd9-win32.exe that is recognized as a virus from Windows.

“aseba-bin-1.5.98-git-c010fd9-win32.exe  è tenuto prigioniero nel cestino dei virus e non vedrà mai più la luce. Esegui una scansione per essere certo che non abbia causato danni.”
Su altro computer con antivirus Symantec il programma è stato scaricato, ma alla richiesta di esecuzione l’antivirus l’ha cancellato dalla cartella dei downloads.

Both Avast and Symantec forbid to execute the exe file. 

How to solve this? any clue?

**Comment by mbonani** [comment]
Hello,
For Avast we see it, I just send to them that is a false positive.  We will see if it resolved the problem. 
when we release we will check that the installer is ok for all virus. A good tool to test is https://www.virustotal.com/#/home/upload

For development version it could that people have to disable their antivirus temporarily

**Comment by stephanemagnenat** [comment]
I wonder whether this problem would be away if we could sign the Windows package.

**Comment by mbonani** [comment]
I got contact with avast and get this answer:

> Thank you for your reply.
> 
> I'd suggest checking these articles about Avast virus policy:
> - Avast Clean Guidelines: https://www.avast.com/faq.php?article=AVKB228
> - Avast File Whitelisting: https://www.avast.com/en-us/faq.php?article=AVKB229
> 
> It is always beneficial to use a valid digital signature on executable files. You can also submit your files for whitelisting before every new released in order to prevent detections.

**Comment by mbonani** [comment]
signature is already in pipeline https://github.com/aseba-community/aseba-windows/issues/3
I add to find the better solution to make it. 

I also forgot: normally now "asebahttp" is not recognized as virus by avast. So Symatec has probably the same feature to provide whitelisting.

**Comment by mbonani** [comment]
signature on windows packet are done, this problem should not appear anymore on latest build.
@paolorossetti do you think your contact can test it?

**Comment by mbonani** [comment]
packet are signed should work
