### ISSUE TITLE
Move Blockly outside Studio

### ISSUE THREAD

**Issue by stephanemagnenat** [aseba-community/aseba#717]
Because of bad built-in browser support in Qt4 builds with recent compilers, we decided to move Blockly out of Studio. The tasks are:
- [ ] Update and test the standalone web-based Blockly code,
- [ ] Package the latter,
- [ ] Update the documentation on the Wiki, 
- [x] Comment out Blockly plugin in Studio.

**Comment by cor3ntin** [comment]
Plugin removed : 7910f738c91d8ce162fa91a1f168b9233c841ae8

**Comment by cor3ntin** [comment]
Moved on Windows & OSX. Let's revisit what we do on linux for 1.7
