### ISSUE TITLE
Update translations

### ISSUE THREAD

**Issue by stephanemagnenat** [aseba-community/aseba#740]
Update translations for Studio, VPL, Thymio firmware updater and Thymio wireless configurator.
- [x] French translation
- [x] German translation
- [x] Italian translation
- [x] Spanish translation
- [x] Greek translation
- [x] Chinese translation

**Comment by basilstotz** [comment]
If you need a hand, I could make the german translations. Any instructions?

**Comment by stephanemagnenat** [comment]
Thanks a lot! Yes, you can the files ending in `_de` from [here](https://github.com/aseba-community/aseba/wiki/translation-release-1.6), and translate them using `qlinguist` as explained [here](http://doc.qt.io/qt-4.8/linguist-translators.html), the general procedure being explained in our [localization guide](https://github.com/aseba-community/aseba/blob/master/localization.md). If you are uncomfortable with git and pull requests, you can send me the updated files by email.

**Comment by paraskevasleivadaros** [comment]
Hello, I'm a native Greek speaker and I would be more than happy to make the Greek translations. Let me know if I can help!

**Comment by stephanemagnenat** [comment]
Thank you very much! The same instruction apply for Greek as German, but with the `_el` postfix in the names.

**Comment by mbonani** [comment]
Paolo will work on italian translation.
You can find standalone qt linguist installer here. https://github.com/lelegard/qtlinguist-installers/releases

**Comment by stephanemagnenat** [comment]
We are now only missing Chinese and Greek translations, and none of them are release blockers, so I mark this item as done in #596 and keep it here for further bookkeeping.

**Comment by stephanemagnenat** [comment]
The Chinese translation is in, any news from the Greek one?

**Comment by paraskevasleivadaros** [comment]
Sorry about that, i had a lot of work and i forgot about them. I will try and make them until the end of this month. I hope that's okay. If not, let me know and i will do my best to have them delivered as soon as possible! :)

**Comment by paraskevasleivadaros** [comment]
Hello, i wanted to inform you that today or tomorrow the translations will be ready!

**Comment by mbonani** [comment]
greek is done
