### ISSUE TITLE
Can't always find aseba_INCLUDE_DIR, needed for examples

### ISSUE THREAD

**Issue by davidjsherman** [aseba-community/aseba#796]
The examples try to explicitly find Aseba includes: 
https://github.com/aseba-community/aseba/blob/29b39bc39dde88f6d8f6489e7cf114d164c73e69/examples/CMakeLists.txt#L3-L5 This can fail in some build environments, such as [Buildroot](https://buildroot.org) and [MXE](http://mxe.cc). In those cases it is necessary to supply e.g. `-Daseba_INCLUDE_DIR=..` to CMake.

(I actually don't understand why examples/CMakeLists.txt, above, sets `aseba_INCLUDE_DIR` twice.)

**Comment by stephanemagnenat** [comment]
These lines were here to simulate system-wide Aseba installation for the examples. Obviously overriding the first INCLUDE_DIR by the second is a bug. I do not remember why it is like this. Maybe removing the second one should work? Anyway, this should be checked again as part of the CMakeLists re-factoring by @cor3ntin .

**Comment by cor3ntin** [comment]
I'd like to remove these lines altogether.

First, I don't see the need for the examples to compile outside of the source directory.
I you need to build the examples from source, then you already have the sources and you will need the dependencies anyway.

Second, if we wanted to support that use case and have the example be completely standalone, I think the best way to do that would be to have a find package

**Comment by davidjsherman** [comment]
On the contrary, it seems to me that examples need to compile anywhere. A teacher who is providing some example code for a class of students, isn't going to provide the Aseba sources, they will expect the students to have installed the sdk.

**Comment by cor3ntin** [comment]
Ok, then we need to add a find_package on all examples

**Comment by cor3ntin** [comment]
Fixed by the new build system -  but examples need to be built in-tree
