### ISSUE TITLE
Enforcing the contribution guidlines

### ISSUE THREAD

**Issue by cor3ntin** [aseba-community/aseba#826]
We should prevent contributors ( including core contributors ) to bypass review and CI on master.
Non-forward push should also never ever be done, security concerns non-withstanding.

This can be setup in `Settings > Branches > Master`

![image](https://user-images.githubusercontent.com/1409019/35922209-44b35d24-0c1d-11e8-8c62-6bc34baa76a1.png)

**Comment by stephanemagnenat** [comment]
I agree, we should be less lazy ;-)

Non-forward push can be used in extreme case for example to correct a mistake, but we can prevent it and temporarily change the settings should the need arise.

**Comment by davidjsherman** [comment]
I really don't like to use technical solutions for social issues; I have confidence in human beings. It should be enough that we agree to wait until review before merging. That is the spirit of the guidelines that I proposed.

**Comment by cor3ntin** [comment]
@stephanemagnenat I disagree. I'd rather have a fixing commit on master that a screwed up history. Mistake happen, no need to hide them. Of course that's only true for public/shared branches & tags. Once again, if someone commits a password or something, there can be exceptions ( hopefully, with reviews, that never happens)

@davidjsherman hope for the best, prepare for the worst :)
Regardless of people intentions, some contributors don't know git enough to not screw up unwillingly, we should help them not make mistakes !
